[build]
  command = "pnpm i --frozen-lockfile && pnpm --filter @apps/student build && pnpm manifest && pnpm sri"
  publish = "apps/student/dist"

[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "10.18.3"

# SPA 라우팅
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
