# netlify.toml  (루트에 위치)

[build]
  command = "pnpm i --frozen-lockfile && pnpm --filter @apps/student build && pnpm manifest && pnpm sri"
  publish = "apps/student/dist"

[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "10.18.3"

# ── SRI를 깨뜨리는 Post Processing(미니파이/번들) 비활성화 ──
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = false
  minify = false

# ── 캐시 정책: index.html은 즉시 갱신, 해시된 에셋은 영구 캐시 ──
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# (선택) CSP 헤더 — index.html에 meta CSP도 주입했으니 헤더/메타 중 하나만 유지해도 됨
# [[headers]]
#   for = "/*"
#   [headers.values]
#     Content-Security-Policy = "default-src 'self'; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self' https://*.supabase.co; worker-src 'self'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'"

# ── SPA 라우팅 ──
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
