name: Deploy (Cloudflare Pages)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-student:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 10.18.3, run_install: false }
      - uses: actions/setup-node@v4
        with: { node-version: '20.x', cache: 'pnpm' }
      - run: corepack enable
      - run: pnpm i --frozen-lockfile=false
      - run: pnpm typecheck
      - run: pnpm -C apps/student build
      - run: |
          [ -f apps/student/public/_redirects ] \
            && cp apps/student/public/_redirects apps/student/dist/_redirects \
            || echo '/* /index.html 200' > apps/student/dist/_redirects
      - run: npm i -g wrangler@3
        env: { NPM_CONFIG_FUND: false, NPM_CONFIG_AUDIT: false, npm_config_unsafe_perm: true }
      - run: wrangler whoami
      - run: wrangler pages project list --json | tee projects.json
      - run: |
          npx --yes jq -e '.[] | select(.name=="quiz-rpg")' projects.json > /dev/null 2>&1 \
          || wrangler pages project create quiz-rpg --production-branch=main
      - run: wrangler pages deploy apps/student/dist --project-name=quiz-rpg  
      
      # ⬇️ wrangler-action 대신 CLI 사용 (npm 전역 설치)
      - name: Install Wrangler (global)
        run: npm i -g wrangler@3
        env:
          NPM_CONFIG_FUND: false
          NPM_CONFIG_AUDIT: false
          npm_config_unsafe_perm: true

      - name: Show Wrangler version
        run: wrangler --version

      - name: Deploy to Cloudflare Pages (student)
        run: >
          wrangler pages deploy apps/student/dist
          --project-name=quiz-rpg
