name: Deploy (Cloudflare Pages)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-student:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      # Cloudflare 자격증명 (리포 시크릿에 저장해둔 값)
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.18.3
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Enable Corepack
        run: corepack enable

      - name: Install deps
        run: pnpm install --frozen-lockfile=false

      - name: Typecheck
        run: pnpm typecheck

      - name: Build student
        run: pnpm -C apps/student build

      - name: Ensure SPA fallback (_redirects)
        run: |
          if [ -f apps/student/public/_redirects ]; then
            cp apps/student/public/_redirects apps/student/dist/_redirects
          else
            echo '/* /index.html 200' > apps/student/dist/_redirects
          fi

      # ⬇️ wrangler-action 대신 CLI 사용 (npm 전역 설치)
      - name: Install Wrangler (global)
        run: npm i -g wrangler@3
        env:
          NPM_CONFIG_FUND: false
          NPM_CONFIG_AUDIT: false
          npm_config_unsafe_perm: true

      - name: Show Wrangler version
        run: wrangler --version

      - name: Deploy to Cloudflare Pages (student)
        run: >
          wrangler pages deploy apps/student/dist
          --project-name=quiz-rpg
