name: Quiz Pack Sync (Sheet → JSON)

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Run even if sheet fetch fails (will still commit if local changes exist)"
        type: boolean
        default: false
  schedule:
    # 매일 아침 6시 KST (UTC 21:00)
    - cron: "0 21 * * *"

permissions:
  contents: write

concurrency:
  group: quiz-pack
  cancel-in-progress: false

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate quiz JSON from Google Sheet
        env:
          # ✅ 레포지토리 Settings → Secrets and variables → Actions 에서 설정
          # Secrets:
          #   - QUIZ_SHEET_ID      (필수: 구글 시트 ID)
          # Variables (옵션):
          #   - QUIZ_SHEET_NAME    (시트 탭명, 비우면 첫 시트)
          #   - SUBJECT_MODE       (strict | allowGEN, 기본 strict)
          #   - GEN_MAP_TO         (GEN을 매핑할 과목, 기본 SOC)
          #   - DIFF_TABLE         ("25,20,15,12,10" 형태, 난이도별 기본 제한 시간)
          SHEET_ID: ${{ secrets.QUIZ_SHEET_ID }}
          SHEET_NAME: ${{ vars.QUIZ_SHEET_NAME }}
          SUBJECT_MODE: ${{ vars.SUBJECT_MODE }}
          GEN_MAP_TO: ${{ vars.GEN_MAP_TO }}
          DIFF_TABLE: ${{ vars.DIFF_TABLE }}
          # 출력 경로: 런타임에서 staticURL('/packs/sample.json')로 읽습니다.
          OUT_PATH: apps/student/public/packs/sample.json
          # 선택: 실패 시에도 커밋은 시도할지
          FORCE: ${{ github.event.inputs.force || 'false' }}
        run: node scripts/sheet_to_quizpack.mjs

      - name: Commit & Push (if changed)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore(quiz-pack): update from Google Sheet"
            git push
          fi
