name: Wearables Catalog Sync (Sheet → JSON)

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Run even if sheet fetch fails (will still commit if local changes exist)"
        type: boolean
        default: false
  schedule:
    # 매일 아침 6시 KST (UTC 21시)
    - cron: "0 21 * * *"

permissions:
  contents: write

concurrency:
  group: wearables-catalog
  cancel-in-progress: false

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate JSON from Google Sheet
        env:
          # ✅ 레포지토리 Settings → Secrets and variables → Actions
          #    - Secrets:    WEAR_SHEET_ID  (값: 구글 시트 ID)
          #    - Variables:  WEAR_SHEET_NAME (예: Wearables) [옵션]
          #    - Variables:  ASSETS_ROOT     (예: https://unluckyidiot16.github.io/assets-common/QuizRpg/)
          SHEET_ID: ${{ secrets.WEAR_SHEET_ID }}
          SHEET_NAME: ${{ vars.WEAR_SHEET_NAME }}
          ASSETS_ROOT: ${{ vars.ASSETS_ROOT }}
          OUT_PATH: apps/student/public/packs/wearables.v1.json
          FORCE: ${{ github.event.inputs.force || 'false' }}
        run: node scripts/sheet_to_wearables.mjs

      - name: Commit & Push (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore(wearables): update catalog from Google Sheet"
            git push
          fi

      # 보호 브랜치면 PR로 전환
      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v6
      #   with:
      #     commit-message: "chore(wearables): update catalog from Google Sheet"
      #     branch: auto/wearables
      #     title: "Wearables: update catalog from Google Sheet"
      #     body: "Automated sync of wearables catalog."
